name: Spide
version: '1.0.1'
main: fr.spide.Spide
api-version: '1.21'
author: herocraftlol
description: >
  Jeu PvP par équipes où les flèches ne blessent pas mais détruisent des blocs.
  Le but est de faire tomber les joueurs adverses en cassant les blocs de leur base.

commands:
  sp:
    description: Commande principale du plugin Spide
    usage: /sp <gui|create|teamlist|hub|<map> ...>
    permission: spide.admin
    permission-message: "§cVous n'avez pas la permission d'utiliser cette commande."

permissions:
  spide.admin:
    description: Permet de configurer les maps Spide
    default: op
  spide.play:
    description: Permet de jouer à Spide
    default: true
